name: deploy-production

on:
  push:
    branches: [main]
  repository_dispatch:
    types: deploy-production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET_PRODUCTION }} --delete
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@main
      #   env:
      #     SLACK_ICON_EMOJI: ":page_with_curl:"
      #     SLACK_USERNAME: docs.xexchange
      #     SLACK_MESSAGE: ${{ secrets.AWS_S3_BUCKET_PRODUCTION }}
      #     SLACK_FOOTER: ""
      #     MSG_MINIMAL: true
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
